name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Configuration de Git pour accepter le répertoire
            sudo git config --global --add safe.directory /var/www/html/portfolio

            # Vérification et création du répertoire si nécessaire
            if [ ! -d "/var/www/html/portfolio" ]; then
              sudo mkdir -p /var/www/html/portfolio
            fi

            # Configuration des permissions de base
            sudo chown -R debian:www-data /var/www/html/portfolio
            sudo chmod -R 775 /var/www/html/portfolio

            # Mise à jour du code
            cd /var/www/html/portfolio
            sudo -u debian git pull origin master

            # Configuration finale des permissions
            sudo find /var/www/html/portfolio -type d -exec chmod 775 {} \;
            sudo find /var/www/html/portfolio -type f -exec chmod 664 {} \;
            sudo chmod -R g+s /var/www/html/portfolio

            # Vérification des permissions
            echo "Vérification des permissions :"
            ls -la /var/www/html/portfolio
