name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "=== Début du déploiement ==="

            # Vérification de l'état actuel
            echo "État actuel du répertoire :"
            ls -la /var/www/html/portfolio

            # Configuration de Git
            echo "Configuration de Git..."
            sudo git config --global --add safe.directory /var/www/html/portfolio
            git config --global --list

            # Vérification et création du répertoire
            if [ ! -d "/var/www/html/portfolio" ]; then
              echo "Création du répertoire portfolio..."
              sudo mkdir -p /var/www/html/portfolio
            fi

            # Configuration des permissions
            echo "Configuration des permissions..."
            sudo chown -R debian:www-data /var/www/html/portfolio
            sudo chmod -R 775 /var/www/html/portfolio

            # Mise à jour du code
            echo "Mise à jour du code..."
            cd /var/www/html/portfolio
            echo "État du dépôt Git avant pull :"
            git status
            sudo -u debian git pull origin master
            echo "État du dépôt Git après pull :"
            git status

            # Configuration finale des permissions
            echo "Configuration finale des permissions..."
            sudo find /var/www/html/portfolio -type d -exec chmod 775 {} \;
            sudo find /var/www/html/portfolio -type f -exec chmod 664 {} \;
            sudo chmod -R g+s /var/www/html/portfolio

            # Vérification finale
            echo "=== Vérification finale ==="
            echo "Contenu du répertoire :"
            ls -la /var/www/html/portfolio
            echo "Derniers commits :"
            git log -n 3 --oneline
            echo "=== Fin du déploiement ==="
