name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "=== Début du déploiement ==="

            # Vérification de la configuration Nginx
            echo "Configuration Nginx :"
            sudo nginx -T | grep -A 20 "server_name portfolio.mfiatuwo.fr"

            # Vérification du répertoire root
            ROOT_DIR="/var/www/html/portfolio"
            echo "Répertoire root : $ROOT_DIR"

            # Vérification de l'état actuel
            echo "État actuel du répertoire :"
            ls -la $ROOT_DIR

            # Configuration de Git
            echo "Configuration de Git..."
            sudo git config --global --add safe.directory $ROOT_DIR
            git config --global --list

            # Vérification et création du répertoire
            if [ ! -d "$ROOT_DIR" ]; then
              echo "Création du répertoire..."
              sudo mkdir -p $ROOT_DIR
            fi

            # Configuration des permissions
            echo "Configuration des permissions..."
            sudo chown -R debian:www-data $ROOT_DIR
            sudo chmod -R 775 $ROOT_DIR

            # Mise à jour du code
            echo "Mise à jour du code..."
            cd $ROOT_DIR

            # Vérification si c'est un dépôt Git
            if [ ! -d ".git" ]; then
              echo "Initialisation du dépôt Git..."
              sudo -u debian git init
              sudo -u debian git remote add origin https://github.com/${{ github.repository }}.git
            fi

            echo "État du dépôt Git avant pull :"
            git status
            sudo -u debian git pull origin master
            echo "État du dépôt Git après pull :"
            git status

            # Configuration finale des permissions
            echo "Configuration finale des permissions..."
            sudo find $ROOT_DIR -type d -exec chmod 775 {} \;
            sudo find $ROOT_DIR -type f -exec chmod 664 {} \;
            sudo chmod -R g+s $ROOT_DIR

            # Vérification finale
            echo "=== Vérification finale ==="
            echo "Contenu du répertoire :"
            ls -la $ROOT_DIR
            echo "Derniers commits :"
            git log -n 3 --oneline

            # Vérification des fichiers PHP
            echo "Vérification des fichiers PHP :"
            ls -la $ROOT_DIR/*.php

            # Vérification de la configuration Nginx
            echo "Vérification de la configuration Nginx :"
            sudo nginx -t

            # Redémarrage de Nginx si nécessaire
            if [ $? -eq 0 ]; then
              echo "Redémarrage de Nginx..."
              sudo systemctl restart nginx
            fi

            # Vérification du statut de Nginx
            echo "Statut de Nginx :"
            sudo systemctl status nginx

            echo "=== Fin du déploiement ==="
